name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, docusaurus-blog-implementation ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (blog)
        run: cd blog && npm ci

      - name: Determine BASE_PATH
        id: base
        run: |
          REPO="$GITHUB_REPOSITORY"             # owner/repo
          REPO_NAME="${REPO#*/}"               # repo
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_PATH=" >> $GITHUB_OUTPUT  # user/org page -> root
          else
            echo "BASE_PATH=/$REPO_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Build Portfolio (Next.js)
        env:
          BASE_PATH: ${{ steps.base.outputs.BASE_PATH }}
        run: |
          echo "Building Next.js portfolio with BASE_PATH='${BASE_PATH}'"
          npm run build:portfolio

      - name: Build Blog (Docusaurus)
        run: |
          echo "Building Docusaurus blog"
          npm run build:blog

      - name: Combine Builds
        run: |
          echo "Combining portfolio and blog builds"
          npm run combine
          # Create .nojekyll to prevent GH Pages from ignoring files/folders starting with _
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
